version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hw02_postgres
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "567234"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hw02"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: hw02_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:567234@db:5432/hw02
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    networks:
      - app_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
